#Based on: https://www.vipinajayakumar.com/continuous-integration-of-latex-projects-with-gitlab-pages.html
#by Vipin Ajayakumar

compile_pdf:
  stage: build
  image: aergus/latex  # use a Docker image for LaTeX from https://hub.docker.com/
  script: pdflatex WSB_ZaawansowaneTechnikiObiektowe.tex; pdflatex WSB_ZaawansowaneTechnikiObiektowe.tex; biber WSB_ZaawansowaneTechnikiObiektowe; biber WSB_ZaawansowaneTechnikiObiektowe; pdflatex WSB_ZaawansowaneTechnikiObiektowe.tex
  artifacts:
    paths:
      - WSB_ZaawansowaneTechnikiObiektowe.pdf  # instruct GitLab to keep the main.pdf file

pages:
  stage: deploy
  script:
    - mkdir public  # create a folder called public
    - cp WSB_ZaawansowaneTechnikiObiektowe.pdf public  # copy the pdf file into the public folder
  artifacts:
    paths: 
      - public  # instruct GitLab to keep the public folder
  only: 
    - master  # deploy the pdf only for commits made to the master branch 